workspace:
  base: /drone
  path: src/github.com/qnib/qwatch

pipeline:
  test:
    image: qnib/golang
    pull: true
    commands:
     - git clone -b v2 https://github.com/go-yaml/yaml.git /drone/src/gopkg.in/yaml.v2
     - git clone -b v2 https://github.com/go-yaml/yaml.git /drone/.cache/govendor/gopkg.in/yaml.v2
     - ./test.sh
    environment:
     - GOPATH=/drone/
  slack:
    image: plugins/slack
    channel: drone
    username: drone
# publish:
#    image: plugins/coverage
#      server: http://wins.ddns.net:8008
#      token: $$GITHUB_API_KEY
#    github_release:
#      api_key: $$GITHUB_API_KEY
#      files: bin/drone/*
#      checksum: sha1
