workspace:
  base: /drone
  path: src/github.com/qnib/qwatch

pipeline:
 unit-test:
    image: qnib/golang:1.7
    commands:
     - ./test.sh
    environment:
     - GOPATH=/drone/

# publish:
#    image: drone/coverage 
#      server: http://wins.ddns.net:8008
#      token: $$GITHUB_API_KEY
#    github_release:
#      api_key: $$GITHUB_API_KEY
#      files: bin/drone/*
#      checksum: sha1
